FROM registry.access.redhat.com/ubi8/ubi:8.8 as java-builder
LABEL maintainer="OpsMx"

ARG JAVA_PACKAGE=java-17-openjdk-jmods
RUN yum -y update && yum -y install --nodocs ${JAVA_PACKAGE}

# Build a custom JRE.
# For now, we will include all modules.  We could try to remove the ones
# we don't need to reduce image size and security attack surface.
WORKDIR /jrebuild
RUN java --list-modules | cut -d'@' -f1 > modules
RUN jlink --output runtime --add-modules `paste -sd, - < modules` --compress 2 --vm server

# Build a minimal base image with our custom Java installed.

FROM registry.access.redhat.com/ubi8/ubi:8.8 AS java-base
LABEL maintainer="OpsMx"
COPY --from=java-builder /jrebuild/runtime /opsmx-java-runtime
ARG OPSMXUSER=1001
ENV JAVA_HOME=/opsmx-java-runtime \
    PATH=${PATH}:/opsmx-java-runtime/bin \
    WORK_DIR=/opsmx/workdir \
    CONF_DIR=/opsmx/conf

# Enabling fips mode
RUN fips-mode-setup --enable

# Setting crypto policies to FIPS
RUN update-crypto-policies --set FIPS

COPY ./gate-web/build/install/gate /opt/gate
RUN mkdir -p /opt/jaeger
COPY ./jaeger/opentelemetry-javaagent.jar /opt/jaeger/opentelemetry-javaagent.jar
#RUN yum -y install java-17-openjdk-devel vim curl net-tools nettle

RUN yum -y install  wget 

RUN yum -y remove  tar  
RUN yum -y remove clean all && rm -rf /var/cache

RUN adduser spinnaker
RUN mkdir -p /opt/gate/plugins && mkdir -p /opt/spinnaker/plugins

#custom plugin zip files adding
ARG CUSTOMPLUGIN_RELEASEVERSION
ENV CUSTOMPLUGIN_RELEASEVERSION=$CUSTOMPLUGIN_RELEASEVERSION
ARG CUSTOMPLUGIN_RELEASE_VERSION
ENV CUSTOMPLUGIN_RELEASE_VERSION=$CUSTOMPLUGIN_RELEASE_VERSION

RUN wget -O Opsmx.VerificationGatePlugin-VerificationPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c https://github.com/OpsMx/Customplugins/releases/download/v${CUSTOMPLUGIN_RELEASEVERSION}/VerificationPlugin-v${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/gate/plugins \
   && wget -O Opsmx.TestVerificationGatePlugin-TestVerificationPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip https://github.com/OpsMx/Customplugins/releases/download/v${CUSTOMPLUGIN_RELEASEVERSION}/TestVerificationPlugin-v${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/gate/plugins \
   && wget -O Opsmx.PolicyGatePlugin-policyPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c  https://github.com/OpsMx/Customplugins/releases/download/v${CUSTOMPLUGIN_RELEASEVERSION}/policyPlugin-v${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/gate/plugins \
   && wget -O Opsmx.PolicyGatePlugin-RbacPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c  https://github.com/OpsMx/Customplugins/releases/download/v${CUSTOMPLUGIN_RELEASEVERSION}/RbacPlugin-v${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/gate/plugins \
   && wget -O Opsmx.VisibilityApprovalPlugin-ApprovalStagePlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c  https://github.com/OpsMx/Customplugins/releases/download/v${CUSTOMPLUGIN_RELEASEVERSION}/ApprovalStagePlugin-v${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/gate/plugins \
    && mv Opsmx.TestVerificationGatePlugin-TestVerificationPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip  /opt/gate/plugins \
    && mv Opsmx.PolicyGatePlugin-policyPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/gate/plugins \
    && mv Opsmx.PolicyGatePlugin-RbacPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/gate/plugins \
    && mv Opsmx.VisibilityApprovalPlugin-ApprovalStagePlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/gate/plugins

#custom plugin zip files adding
ARG CUSTOMPLUGIN_RELEASEORG
ENV CUSTOMPLUGIN_RELEASEORG=$CUSTOMPLUGIN_RELEASEORG
ARG CUSTOMPLUGIN_RELEASEREPO
ENV CUSTOMPLUGIN_RELEASEREPO=$CUSTOMPLUGIN_RELEASEREPO
RUN wget -O Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c https://github.com/${CUSTOMPLUGIN_RELEASEORG}/${CUSTOMPLUGIN_RELEASEREPO}/releases/download/v${CUSTOMPLUGIN_RELEASE_VERSION}/armory-observability-plugin-v${CUSTOMPLUGIN_RELEASE_VERSION}.zip -P /opt/gate/plugins
RUN mv Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/gate/plugins
COPY custom-plugin.json /opt/spinnaker/plugins/plugins.json

#COPY ./docker/ubi8/observability-plugin.json /opt/gate/plugins/plugins.json

RUN chown -R spinnaker:spinnaker /opt/spinnaker

RUN chmod -R 777 /opt/gate/plugins/
RUN chown -R spinnaker:spinnaker /opt/
USER spinnaker
CMD ["/opt/gate/bin/gate"]
